const CONFIG = {
  API_URL: "https://script.google.com/macros/s/AKfycbyeJ1igEXpdlO3uciGIOz76iBGXws4mbLaombgOF1iuIG7sQcg4l02aN3AAQXH3QAEmTA/exec",
  ORG_NAME: "Falla Castielfabib - Marques de San Juan",
  ADMIN_EMAIL: "castielfabibfalla@gmail.com",
  TZ: "Europe/Madrid",
  DEMO: true,
  ALLOW_DEMO_TOGGLE: true,
  ADMIN_SECRET: "vF7tQ9mL2xY5kZ8pR4nA6sJ1",
  DEMO_EVENTS: [
    {
      id: "cena2026",
      title: "Cena de la Falla",
      title_val: "Sopar de la Falla",
      date: "2026-02-14",
      time: "21:00",
      place: "Casal",
      place_val: "Casal",
      description: "Cena informal para empezar el año fallero.",
      description_val: "Sopar informal per encetar l'any faller.",
      model: "basic",
      extra_label: "",
      limit: 25,
      status: "active",
      attendees: ["Laura Marti", "Alex", "Carmen", "Javi", "Marta"],
    },
    {
      id: "camiseta",
      title: "Pedido de camisetas",
      title_val: "Comanda de samarretes",
      date: "2026-02-20",
      time: "19:30",
      place: "Casal",
      place_val: "Casal",
      description: "Elige tu talla para la camiseta de la falla.",
      description_val: "Tria la teua talla per a la samarreta de la falla.",
      model: "extended",
      extra_label: "Talla",
      extra_label_val: "Talla",
      limit: 0,
      status: "active",
      attendees: ["Neus", "Paco", "Toni", "Sara"],
    },
    {
      id: "halloween",
      title: "Desfile de Halloween",
      title_val: "Desfilada de Halloween",
      date: "2026-10-31",
      time: "18:30",
      place: "Barrio",
      place_val: "Barri",
      description: "Apunta tu disfraz y participa en el desfile.",
      description_val: "Apunta la teua disfressa i participa en la desfilada.",
      model: "extended",
      extra_label: "Disfraz",
      extra_label_val: "Disfressa",
      limit: 40,
      status: "active",
      attendees: ["Claudia", "Hector", "Paula", "Marcos", "Vero", "Anita"],
    },
  ],
};

window.CONFIG = CONFIG;
